name: Run Flake8

on: # trigger
  push: # when pushed
    branches: # to which branch
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: # 수동으로 켜기

jobs: # what to do
  flake8:
    name: flake8
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install flake8
          python -m flake8 .
        
